#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

# Behavior
bspc config pointer_follows_focus true		# place pointer on new window when focused
bspc config focus_follows_pointer true		# do not require a click to focus a new window
bspc config pointer_follows_monitor true	# place pointer on new monitor when changed focus

# Appearance
bspc config border_width			2
bspc config window_gap				20
bspc config focused_border_color	"#7FB4FF"

bspc config split_ratio				0.5
bspc config borderless_monocle		true
bspc config single_monocle			true
bspc config gapless_monocle			true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall "polybar"
polybar example &
polybar example2 &
