#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

# Appearance
bspc config border_width	2
bspc config window_gap		20
bspc config single_monocle	true
bspc config gapless_monocle	true
bspc config borderless_monocle	true

# Functionality
bspc config focus_follows_pointer true
bspc config split_ratio		0.5

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a "Qalculate-gtk" state=floating
bspc rule -a Zathura state=tiled

killall "polybar"
polybar main &
xdo lower -N "Polybar"
