#!/bin/bash

# Script for connecting to a vpn server through OpenVPN
# Prompts user for which server they'd like to connect to

# openvpn --config /home/jacob/PrivateVPN/PrivateVPN-TUN/UDP/*
if [ $(whoami) != "root" ]; then
	echo "Root access required. Please try again using sudo."
	exit
fi

echo "Enter server country (usa, sweden, canada, uk)"
read server

case $server in
	sweden)
		openvpn --config /home/jacob/PrivateVPN/PrivateVPN-TUN/UDP/PrivateVPN-SE-Stockholm-TUN-1194.ovpn
		;;
	usa)
		openvpn --config /home/jacob/PrivateVPN/PrivateVPN-TUN/UDP/PrivateVPN-US-Buffalo-TUN-1194.ovpn
		;;
	canada)
		openvpn --config /home/jacob/PrivateVPN/PrivateVPN-TUN/UDP/PrivateVPN-CA-Toronto 1-TUN-1194.ovpn
		;;
	uk)
		openvpn --config /home/jacob/PrivateVPN/PrivateVPN-TUN/UDP/PrivateVPN-UK-London 5-TUN-1194.ovpn
		;;
	*)
		echo "Unknown server. Try (sweden, usa, canada, or uk)"
		;;
esac
