#!/bin/sh

(( $(mpc --host 127.0.0.1 --port 6601 | sed -n 2p | awk '{print $3}' | sed 's/\/.*//g' | sed 's/^.*://g') < 3 )) && mpc --host 127.0.0.1 --port 6601 prev || mpc --host 127.0.0.1 --port 6601 seek 0:0:0
